### ISSUE TITLE
Cosmetics / variables naming

### ISSUE THREAD

**Issue by david-m-m** [datenschuft/SMA-EM#14]
Hi,
I'd like to propose a little renaming of variables and names. 
As far as I can see the meaning of "regard" is usually not related to electricity. "Regard" seems to describe a relation (german "bezugnehmend"/"bezogen auf"). 
Therefore I think that "consume" would be more clear and also fitting "supply"...
What do you think?

**Comment by datenschuft** [comment]
Right; I will consider the changes at the next uploads

**Comment by datenschuft** [comment]
variables renamed with upload e3d49b0
