### ISSUE TITLE
psupply / qsupply / ssupply

### ISSUE THREAD

**Issue by gobartos** [datenschuft/SMA-EM#19]
Hello and thanks! I have a SMA Tripower (three phases) and I can't understand very well what source is what. So what does psupply measure exactly? and p1supply p2supply and p3supply are the phases? Thanks. i'm especially interested in these values: * net return and net consumption. Kindly Bart

**Comment by jhagberg** [comment]
Check the SMA pdf or check my clone if that is more easy to understand https://github.com/jhagberg/sma-em-influxdb
there you find the link to the PDF also.

**Comment by gobartos** [comment]
Thanks but unfortunately I can't find values like 'psupply' of 'qsupply' anywhere in your clone or in documents by SMA. I have a Tripower + SMA Home Manager 2.0 (which contains an Energy Meter)

**Comment by datenschuft** [comment]
Hi Bart

first of all i have no sma inverters.

i fyou have a inverter (independently if one phase or 3 phase) it shoudl generate energy.
if not (on sunny days) something was wrong.

Electric power is represented by p.
There is also a reactive power q and s.
https://en.wikipedia.org/wiki/AC_power#Reactive_power

So all energy from your inverter is supply power.

The SMA-EM or HomeManager2 (if the installation was done right) measures the electric power you consume from the main grid or supply to the main grid.

All measurements are prefixed with p,q or s.
Example: p1consume = Electical Energy (P) on phase 1 in direction "consume"

You could use the SMA-EM to measure the electic power and the direction. So you could proberby control some electric devices to control your power consumption. no matter if you use a Inverter or not.

**Comment by gobartos** [comment]
Many thanks Florian, this helps! Only the p is important in my case!
