### ISSUE TITLE
Expose "counter" as well

### ISSUE THREAD

**Issue by alfh** [datenschuft/SMA-EM#2]
Hi
This script was exactly what I was looking for. I just got my SMA energy meter up and running a week ago.

I want to read the values and put into a database, and I can use this script as a basis.
When I use the http://www.eb-systeme.de/?page_id=1545, I see that the energy meter also delivers a "counter" value, which is the total number of kWh.
Do you know the message format of the energy meter, so you can pick up this value as well, and display it ?

I am wondering if I should get another energy meter, and use one to measure the PV production, and the other to measure the electricity delivered to the grid and the electricity used in my household.

Let me know if you need any help with development or testing

Alf Høgemark
www.kanonbra.com

**Comment by datenschuft** [comment]
Hello. I'm on vacation.
You will hear from me in a few days.

see the web-page http://www.eb-systeme.de/?page_id=1240 (Nico Treffkorn)
the counter values are also described at the page.
search for "Bezugszähler" 

maybe i will add the counters to the script in the next weeks...

**Comment by alfh** [comment]
Hi
I've looked into Nico Treffkorn's page, and it helps, but I do not fully understand it.

I've added the following to your script :

# These seems to be correct

  print ('P Supply counter',(hex2dec(smainfoasci[88:96])/3600)/1000);
  print ('P Feed counter',(hex2dec(smainfoasci[128:136])/3600)/1000);

# This is not correct

  print ('P Supply counter test',(hex2dec(smainfoasci[66:74]))/10);
  print ('S Supply counter',(hex2dec(smainfoasci[226:234])/3600)/1000);
  print ('S Feed counter',(hex2dec(smainfoasci[272:280])/3600)/1000);

However, I do not fully understand what indexes to use into the smainfoasci, and from Nico's page, and the data in my packages, it seems like the same data is represented both in 00104 and 00108 packages.

But the counters seems to be there, just need to investigate more to get the correct info out.

**Comment by alfh** [comment]
The following data 

> 00010400000021a20 0010800000000001d6c58f0 = P supply counter
> 00020400000000000 0020800000000007b101be0 = P feed counter
> 00030400000000000 00308000000000008bba6e0
> 00040400000002a40 00408000000000002664cf0
> 00090400000021bc0 00908000000000020159238 = S supply counter
> 000a0400000000000 00a0800000000007b96fb88 = S feed counter
>  00108 seems to be P supply counter content
>  00208 seems to be P feed counter content
>  00908 seems to be S supply counter content
>  00a08 seems to be S feed counter content
> The values, for example 7b96fb88 needs to be divided by e10 (3600) to get the values in kWh / kVAh

Alf

**Comment by datenschuft** [comment]
i added some counters in the branch "counters".
I will check the values with my Elster As 1440 in the next days.

the counter values are still unverified

The counters are located at
pregardcounter=hex2dec(smainfoasci[80:96])/3600000
psurpluscounter=hex2dec(smainfoasci[120:136])/3600000
and you have to devide by 3600 to get Wh and divide by 1000 again to get kWh or kVAh

**Comment by alfh** [comment]
Hi
I've tested the counters branch now, and the values match what my EMview app is showing (the app from Nico, I think).
So the values seems correct.
However, I think some of your units are wrong, it is not all kWh, some are kVAh and kvarh.

I also think the unit is "var" and not "VAr", but I am no expert, I read https://en.wikipedia.org/wiki/Volt-ampere_reactive

Thanks for you effort.
Alf

**Comment by datenschuft** [comment]
i have added the other counters also to the counters-branch and updated the units.
thank you.

**Comment by alfh** [comment]
The counters for the three phases individually works fine for me as well.
I think you can merge this functionality to master branch.

Regards
Alf

**Comment by datenschuft** [comment]
Thanks for testing;
merged to master branch

**Comment by jhagberg** [comment]
I just tested today also seams to work. So you have counter on each Phase also?

**Comment by datenschuft** [comment]
Yes; counters for L1 P,Q and S in both directions (also for L2 and L3)

**Comment by jhagberg** [comment]
aha nice!
Thanks!
