### ISSUE TITLE
Additional Parameters?

### ISSUE THREAD

**Issue by giase82** [datenschuft/SMA-EM#20]
Hi!

Thanks for this work, this is really helpful in connection with a smarthomeNG-plugin. I wonder if there is a chance to extract other PV-related data, such as total power and current internal consumption (basically all info which SMA has available on sunnyportal). From what I understand from the Energy-Meter protocoll, there are no such parameters, but I am not sure if  inverters also broadcast some of their parameters. Do you know? Would it be possible to add that if those telegrams exist?

Thanks,
//giase

**Comment by datenschuft** [comment]
Hi 
You are right. SMA Energy - Meter don't know these values.
But you could calculate them if you know the PV data from SMA Inverters via Modbus...
Here https://github.com/datenschuft/SMA-EM/blob/master/features/smamodbus.py is a feature to get these values from the SMA Inverter via ModBus. 
I have no SMA-Inverter so i clouldn't test the feature but it seams to work.

I think smarthomeNG could also read the values via ModBus, so you should be able to calculate the nessersary values.

With kind regards
datenschuft

**Comment by giase82** [comment]
Hi! 

Ok, thanks a lot for the pointer, I am going to look into this once I find time.

Cheers,
//giase

**Comment by giase82** [comment]
One more thing: Can you give me a pointer about how to try this out in the easiest possible way? I think the question is basically how I have to configure the modbus-feature. Any hints?

Thanks!

**Comment by datenschuft** [comment]
as described in features/pvdata.py
add pvdata to the feature list in the config file

and you could also define the wanted registers
[FEATURE-pvdata]
    # How frequently to send updates over (defaults to 20 sec)
    min_update=20
    #debug output
    debug=0
    #inverter connection
    inv_host = <inverter ip>
    inv_port = 502
    inv_modbus_id = 3
    inv_manufacturer = SMA
    #['address', 'type', 'format', 'description', 'unit', 'value']
    registers = [
        ['30057', 'U32', 'RAW', 'serial', ''],
        ['30201','U32','ENUM','Status',''],
        ['30051','U32','ENUM','DeviceClass',''],
        ['30053','U32','ENUM','DeviceID',''],
        ['40631', 'STR32', 'UTF8', 'Device Name', ''],
        ['30775', 'S32', 'FIX0', 'AC Power', 'W'],
        ['30813', 'S32', 'FIX0', 'AC apparent power', 'VA'],
        ['30977', 'S32', 'FIX3', 'AC current', 'A'],
        ['30783', 'S32', 'FIX2', 'AC voltage', 'V'],
        ['30803', 'U32', 'FIX2', 'grid frequency', 'Hz'],
        ['30773', 'S32', 'FIX0', 'DC power', 'W'],
        ['30771', 'S32', 'FIX2', 'DC input voltage', 'V'],
        ['30777', 'S32', 'FIX0', 'Power L1', 'W'],
        ['30779', 'S32', 'FIX0', 'Power L2', 'W'],
        ['30781', 'S32', 'FIX0', 'Power L3', 'W'],
        ['30953', 'S32', 'FIX1', u'device temperature', u'\xb0C'],
        ['30517', 'U64', 'FIX3', 'daily yield', 'kWh'],
        ['30513', 'U64', 'FIX3', 'total yield', 'kWh'],
        ['30521', 'U64', 'FIX0', 'operation time', 's'],
        ['30525', 'U64', 'FIX0', 'feed-in time', 's'],
        ['30975', 'S32', 'FIX2', 'intermediate voltage', 'V'],
        ['30225', 'S32', 'FIX0', 'Isolation resistance', u'\u03a9'],
        ['30581', 'U32', 'FIX0', u'energy from grid', 'Wh'],
        ['30583', 'U32', 'FIX0', u'energy to grid', 'Wh'],
        ['30865', 'S32', 'FIX0', 'Power from grid', 'W'],
        ['30867', 'S32', 'FIX0', 'Power to grid', 'W']
    ]
