### ISSUE TITLE
Issues with SMA softwareversion ver.2.03.4.R

### ISSUE THREAD

**Issue by stei-f** [datenschuft/SMA-EM#21]
I've recieved a remote update for my Home Manager, see log:

> Info	12/8/2019 12:50:59 AM	Home Manager 2 058	Update to ver.2.03.4.R successful	
> Info	12/8/2019 12:19:06 AM	Home Manager 2 058	Update started

Starting this day the recieved values became wrong or cannot be used by me anymore (see log):
> #Date,Time,SN,device-name,
> #followed by em-${SN}-pregard em-${SN}-psurplus em-${SN}-p1regard em-${SN}-p1surplus em-${SN}-p2regard em-${SN}-p2surplus em-${SN}-p3regard em-${SN}-p3surplus wr-3051XXXXX-phase1pac wr-3051XXXXX-phase2pac wr-3051XXXXX-phase3pac em-${SN}-pregardcounter em-${SN}-p1regardcounter em-${SN}-p2regardcounter em-${SN}-p3regardcounter em-${SN}-psurpluscounter em-${SN}-p1surpluscounter em-${SN}-p2surpluscounter em-${SN}-p3surpluscounter

> 2019-12-08,01:54:02,3002850XXX,sma-homemanager,327.3000,0.0000,82.0000,0.0000,134.6000,0.0000,110.6000,0.0000,0,0,0,2023.9586,460.4444,880.0240,857.9690,8762.6965,3153.2906,2842.7966,2941.0884
> 2019-12-08,01:55:02,3002850XXX,sma-homemanager,325.4000,0.0000,4999.8000,165760632.0000,83.7000,316809648.0000,79.9000,308869704.0000,0,0,0,2023.9656,966368.0245,1521134.9976,1395865.4822,8762.6965,0.4011,0.7652,1.1292

Any ideas how to fix this? Seems like the structure of the datagram did change (rearragned fields?).

sma-em did run stable for more than a year, would be a shame to loose the ability for the detailed info per phase. 

regards Frank

**Comment by datenschuft** [comment]
Hi frank.
I dont have a Home Manager, I own only a old SMA-EM (no firmware updates found.)
I added a sma-em-capture-package.py - Script.
Could you provide the output of the script, so i could check if there is a version mark or anyhing else to check/phrase old and new packages.

**Comment by stei-f** [comment]
Cannot find a proper format to past here, so just plain text.

`----raw-1024---`
b'SMA\x00\x00\x04\x02\xa0\x00\x00\x00\x01\x02L\x00\x10`i\x01t\xb2\xfb\xdb\na3\xfe\xa4\x00\x01\x04\x00\x00\x00\x00\x00\x00\x01\x08\x00\x00\x00\x00\x01\xd6[.\xf8\x00\x02\x04\x00\x00\x00\xbe\x80\x00\x02\x08\x00\x00\x00\x00\x07\x81\x86E`\x00\x03\x04\x00\x00\x00\x17x\x00\x03\x08\x00\x00\x00\x00\x0144\xf6\x90\x00\x04\x04\x00\x00\x00\x00\x00\x00\x04\x08\x00\x00\x00\x00\x00\xd5#\xa7P\x00\t\x04\x00\x00\x00\x00\x00\x00\t\x08\x00\x00\x00\x00\x02\x0fv\xbb\xf8\x00\n\x04\x00\x00\x00\xbf\xf0\x00\n\x08\x00\x00\x00\x00\x07\xac\xcc\x0c\xa0\x00\r\x04\x00\x00\x00\x03\xe0\x00\x0e\x04\x00\x00\x00\xc3<\x00\x15\x04\x00\x00\x00\x00\x00\x00\x15\x08\x00\x00\x00\x00\x00jb\xee\x80\x00\x16\x04\x00\x00\x00B9\x00\x16\x08\x00\x00\x00\x00\x02\xb4\xc4\xfa \x00\x17\x04\x00\x00\x00\x07\x16\x00\x17\x08\x00\x00\x00\x00\x00d>U\x08\x00\x18\x04\x00\x00\x00\x00\x00\x00\x18\x08\x00\x00\x00\x00\x00EC\xec0\x00\x1d\x04\x00\x00\x00\x00\x00\x00\x1d\x08\x00\x00\x00\x00\x00\x87z=H\x00\x1e\x04\x00\x00\x00B\x99\x00\x1e\x08\x00\x00\x00\x00\x02\xc4G\xe0 \x00\x1f\x04\x00\x00\x00\x1d\x15\x00 \x04\x00\x00\x03\x80\xbb\x00!\x04\x00\x00\x00\x03\xe2\x00)\x04\x00\x00\x00\x00\x00\x00)\x08\x00\x00\x00\x00\x00\xcc\xc2b\xe0\x00*\x04\x00\x00\x00=j\x00*\x08\x00\x00\x00\x00\x02n\xbf)\x88\x00+\x04\x00\x00\x00\tt\x00+\x08\x00\x00\x00\x00\x00u\x08\xddh\x00,\x04\x00\x00\x00\x00\x00\x00,\x08\x00\x00\x00\x00\x00P\x11\xe9x\x001\x04\x00\x00\x00\x00\x00\x001\x08\x00\x00\x00\x00\x00\xe7\xdb\xc0\xa8\x002\x04\x00\x00\x00>#\x002\x08\x00\x00\x00\x00\x02~E=\xc0\x003\x04\x00\x00\x00\x1a\xc2\x004\x04\x00\x00\x03\x8e\xb2\x005\x04\x00\x00\x00\x03\xdc\x00=\x04\x00\x00\x00\x00\x00\x00=\x08\x00\x00\x00\x00\x00\xc6T\xc4 \x00>\x04\x00\x00\x00>\xdd\x00>\x08\x00\x00\x00\x00\x02\x85!\t\xa8\x00?\x04\x00\x00\x00\x06\xed\x00?\x08\x00\x00\x00\x00\x00x~\xa8\xd8\x00@\x04\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00]^\xb90\x00E\x04\x00\x00\x00\x00\x00\x00E\x08\x00\x00\x00\x00\x00\xe1K,\x88\x00F\x04\x00\x00\x00?>\x00F\x08\x00\x00\x00\x00\x02\x97>i(\x00G\x04\x00\x00\x00\x1bi\x00H\x04\x00\x00\x03\x88i\x00I\x04\x00\x00\x00\x03\xe2\x90\x00\x00\x00\x02\x03\x04R\x00\x00\x00\x00'
`----asci---`
b'534d4100000402a000000001024c001060690174b2fbdb0a6133fea400010400000000000001080000000001d65b2ef8000204000000be80000208000000000781864560000304000000177800030800000000013434f69000040400000000000004080000000000d523a750000904000000000000090800000000020f76bbf8000a04000000bff0000a080000000007accc0ca0000d0400000003e0000e04000000c33c001504000000000000150800000000006a62ee8000160400000042390016080000000002b4c4fa2000170400000007160017080000000000643e5508001804000000000000180800000000004543ec30001d040000000000001d080000000000877a3d48001e040000004299001e080000000002c447e020001f040000001d1500200400000380bb00210400000003e200290400000000000029080000000000ccc262e0002a040000003d6a002a0800000000026ebf2988002b040000000974002b0800000000007508dd68002c040000000000002c0800000000005011e97800310400000000000031080000000000e7dbc0a80032040000003e2300320800000000027e453dc00033040000001ac20034040000038eb200350400000003dc003d040000000000003d080000000000c654c420003e040000003edd003e080000000002852109a8003f0400000006ed003f080000000000787ea8d8004004000000000000400800000000005d5eb93000450400000000000045080000000000e14b2c880046040000003f3e0046080000000002973e69280047040000001b69004804000003886900490400000003e2900000000203045200000000'

At the end there seems to be the version: 
`\x00\x02\x03\x04R\x00\x00\x00\x00$`
`0203045200000000$`
(because it was updated to 2.3.4R)

**Comment by datenschuft** [comment]
thx. i'll check the results

**Comment by stei-f** [comment]
See also this link if you not already found it...
http://www.eb-systeme.de/?page_id=3005

**Comment by datenschuft** [comment]
Datagram changed, Pull Request "Datagram parser #18" should work.
Dealing with some extra parser settings - stay tuned

**Comment by stei-f** [comment]
Here is a quick fix for the smaem.py, that works for me. Not really tested, just quickly hacked together. Looks good so far. But may not be of much use for you, as you do not use the "old" names of the emparts anymore (as I have seen).

I've left the old assignments in, that gets immediately overwritten by the new ones for comparision.

regards Frank


```
import struct
import binascii

# function to transform HEX to DEC
def hex2dec(s):
    """return the integer value of a hexadecimal string s"""
    return int(s, 16)

# clean exit
def abortprogram(signal,frame):
    # Housekeeping -> nothing to cleanup
    print('STRG + C = end program')
    sys.exit(0)

def readObis(s):
  obis=(hex2dec(s[0:2]),hex2dec(s[2:4]),hex2dec(s[4:6]),hex2dec(s[6:8]))
  return obis

def readem(sock):
  smainfo=sock.recv(608)
  smainfoasci=binascii.b2a_hex(smainfo)

  # split the received message to seperate vars
  # summary
  # regard/Bezug=getting energy from main grid
  # surplus/surplus=putting energy to the main grid
  OBIS = {}

  #print (smainfoasci)

  #i=0
  #print( smainfoasci[i:i+8] )
  #i+=8


  smaserial=hex2dec(smainfoasci[40:48])
  i=56
  loop=1
  while loop:
    #print(smainfoasci[i:i+8])
    o = readObis(smainfoasci[i:i+8])
    i+=8
    oTxt = ".".join(str(x) for x in o)
    size = o[2]*2
    if( o[0] == 144 ):
      size=8
    if( size ):
      #print(smainfoasci[i:i+size])
      OBIS[oTxt]=hex2dec(smainfoasci[i:i+size])
      i+=size
      #print( oTxt + ": " + str(OBIS[oTxt]) )
    else:
      loop = 0

  pregard=hex2dec(smainfoasci[64:72])/10
  pregardcounter=hex2dec(smainfoasci[80:96])/3600000
  psurplus=hex2dec(smainfoasci[104:112])/10
  psurpluscounter=hex2dec(smainfoasci[120:136])/3600000
  qregard=hex2dec(smainfoasci[144:152])/10
  qregardcounter=hex2dec(smainfoasci[160:176])/3600000
  qsurplus=hex2dec(smainfoasci[184:192])/10
  qsurpluscounter=hex2dec(smainfoasci[200:216])/3600000
  sregard=hex2dec(smainfoasci[224:232])/10
  sregardcounter=hex2dec(smainfoasci[240:256])/3600000
  ssurplus=hex2dec(smainfoasci[264:272])/10
  ssurpluscounter=hex2dec(smainfoasci[280:296])/3600000
  cosphi=hex2dec(smainfoasci[304:312])/1000
  #L1
  p1regard=hex2dec(smainfoasci[320:328])/10
  p1regardcounter=hex2dec(smainfoasci[336:352])/3600000
  p1surplus=hex2dec(smainfoasci[360:368])/10
  p1surpluscounter=hex2dec(smainfoasci[376:392])/3600000
  q1regard=hex2dec(smainfoasci[400:408])/10
  q1regardcounter=hex2dec(smainfoasci[416:432])/3600000
  q1surplus=hex2dec(smainfoasci[440:448])/10
  q1surpluscounter=hex2dec(smainfoasci[456:472])/3600000
  s1regard=hex2dec(smainfoasci[480:488])/10
  s1regardcounter=hex2dec(smainfoasci[496:512])/3600000
  s1surplus=hex2dec(smainfoasci[520:528])/10
  s1surpluscounter=hex2dec(smainfoasci[536:552])/3600000
  thd1=hex2dec(smainfoasci[560:568])/1000
  v1=hex2dec(smainfoasci[576:584])/1000
  cosphi1=hex2dec(smainfoasci[592:600])/1000
  #L2
  p2regard=hex2dec(smainfoasci[608:616])/10
  p2regardcounter=hex2dec(smainfoasci[624:640])/3600000
  p2surplus=hex2dec(smainfoasci[648:656])/10
  p2surpluscounter=hex2dec(smainfoasci[664:680])/3600000
  q2regard=hex2dec(smainfoasci[688:696])/10
  q2regardcounter=hex2dec(smainfoasci[704:720])/3600000
  q2surplus=hex2dec(smainfoasci[728:736])/10
  q2surpluscounter=hex2dec(smainfoasci[744:760])/3600000
  s2regard=hex2dec(smainfoasci[768:776])/10
  s2regardcounter=hex2dec(smainfoasci[784:800])/3600000
  s2surplus=hex2dec(smainfoasci[808:816])/10
  s2surpluscounter=hex2dec(smainfoasci[824:840])/3600000
  thd2=hex2dec(smainfoasci[848:856])/1000
  v2=hex2dec(smainfoasci[864:872])/1000
  cosphi2=hex2dec(smainfoasci[880:888])/1000
  #L3
  p3regard=hex2dec(smainfoasci[896:904])/10
  p3regardcounter=hex2dec(smainfoasci[912:928])/3600000
  p3surplus=hex2dec(smainfoasci[936:944])/10
  p3surpluscounter=hex2dec(smainfoasci[952:968])/3600000
  q3regard=hex2dec(smainfoasci[976:984])/10
  q3regardcounter=hex2dec(smainfoasci[992:1008])/3600000
  q3surplus=hex2dec(smainfoasci[1016:1024])/10
  q3surpluscounter=hex2dec(smainfoasci[1032:1048])/3600000
  s3regard=hex2dec(smainfoasci[1056:1064])/10
  s3regardcounter=hex2dec(smainfoasci[1072:1088])/3600000
  s3surplus=hex2dec(smainfoasci[1096:1104])/10
  s3surpluscounter=hex2dec(smainfoasci[1112:1128])/3600000
  thd3=hex2dec(smainfoasci[1136:1144])/1000
  v3=hex2dec(smainfoasci[1152:1160])/1000
  cosphi3=hex2dec(smainfoasci[1168:1176])/1000

  pregard=OBIS["0.1.4.0"]/10
  pregardcounter=OBIS["0.1.8.0"]/3600000
  psurplus=OBIS["0.2.4.0"]/10
  psurpluscounter=OBIS["0.2.8.0"]/3600000
  qregard=OBIS["0.3.4.0"]/10
  qregardcounter=OBIS["0.3.8.0"]/3600000
  qsurplus=OBIS["0.4.4.0"]/10
  qsurpluscounter=OBIS["0.4.8.0"]/3600000
  sregard=OBIS["0.9.4.0"]/10
  sregardcounter=OBIS["0.9.8.0"]/3600000
  ssurplus=OBIS["0.10.4.0"]/10
  ssurpluscounter=OBIS["0.10.8.0"]/3600000
  cosphi=OBIS["0.13.4.0"]/1000
  if "0.14.4.0" in OBIS:
    freqency=OBIS["0.14.4.0"]/1000

  #L1
  p1regard=OBIS["0.21.4.0"]/10
  p1regardcounter=OBIS["0.21.8.0"]/3600000
  p1surplus=OBIS["0.22.4.0"]/10
  p1surpluscounter=OBIS["0.22.8.0"]/3600000
  q1regard=OBIS["0.23.4.0"]/10
  q1regardcounter=OBIS["0.23.8.0"]/3600000
  q1surplus=OBIS["0.24.4.0"]/10
  q1surpluscounter=OBIS["0.24.8.0"]/3600000
  s1regard=OBIS["0.29.4.0"]/10
  s1regardcounter=OBIS["0.29.8.0"]/3600000
  s1surplus=OBIS["0.30.4.0"]/10
  s1surpluscounter=OBIS["0.30.8.0"]/3600000
  thd1=OBIS["0.31.4.0"]/1000
  v1=OBIS["0.32.4.0"]/1000
  cosphi1=OBIS["0.33.4.0"]/1000

  #L2
  p2regard=OBIS["0.41.4.0"]/10
  p2regardcounter=OBIS["0.41.8.0"]/3600000
  p2surplus=OBIS["0.42.4.0"]/10
  p2surpluscounter=OBIS["0.42.8.0"]/3600000
  q2regard=OBIS["0.43.4.0"]/10
  q2regardcounter=OBIS["0.43.8.0"]/3600000
  q2surplus=OBIS["0.44.4.0"]/10
  q2surpluscounter=OBIS["0.44.8.0"]/3600000
  s2regard=OBIS["0.49.4.0"]/10
  s2regardcounter=OBIS["0.49.8.0"]/3600000
  s2surplus=OBIS["0.50.4.0"]/10
  s2surpluscounter=OBIS["0.50.8.0"]/3600000
  thd2=OBIS["0.51.4.0"]/1000
  v2=OBIS["0.52.4.0"]/1000
  cosphi2=OBIS["0.53.4.0"]/1000

  #L3
  p3regard=OBIS["0.61.4.0"]/10
  p3regardcounter=OBIS["0.61.8.0"]/3600000
  p3surplus=OBIS["0.62.4.0"]/10
  p3surpluscounter=OBIS["0.62.8.0"]/3600000
  q3regard=OBIS["0.63.4.0"]/10
  q3regardcounter=OBIS["0.63.8.0"]/3600000
  q3surplus=OBIS["0.64.4.0"]/10
  q3surpluscounter=OBIS["0.64.8.0"]/3600000
  s3regard=OBIS["0.69.4.0"]/10
  s3regardcounter=OBIS["0.69.8.0"]/3600000
  s3surplus=OBIS["0.70.4.0"]/10
  s3surpluscounter=OBIS["0.70.8.0"]/3600000
  thd3=OBIS["0.71.4.0"]/1000
  v3=OBIS["0.72.4.0"]/1000
  cosphi3=OBIS["0.73.4.0"]/1000

  #Returning values
  emparts = {'serial':smaserial,'pregard':pregard,'pregardcounter':pregardcounter,'psurplus':psurplus,'psurpluscounter':psurpluscounter,
  'sregard':sregard,'sregardcounter':sregardcounter,'ssurplus':ssurplus,'ssurpluscounter':ssurpluscounter,
  'qregard':qregard,'qregardcounter':qregardcounter,'qsurplus':qsurplus,'qsurpluscounter':qsurpluscounter,
  'cosphi':cosphi,
  'p1regard':p1regard,'p1regardcounter':p1regardcounter,'p1surplus':p1surplus,'p1surpluscounter':p1surpluscounter,
  's1regard':s1regard,'s1regardcounter':s1regardcounter,'s1surplus':s1surplus,'s1surpluscounter':s1surpluscounter,
  'q1regard':q1regard,'q1regardcounter':q1regardcounter,'q1surplus':q1surplus,'q1surpluscounter':q1surpluscounter,
  'v1':v1,'thd1':thd1,'cosphi1':cosphi1,
  'p2regard':p2regard,'p2regardcounter':p2regardcounter,'p2surplus':p2surplus,'p2surpluscounter':p2surpluscounter,
  's2regard':s2regard,'s2regardcounter':s2regardcounter,'s2surplus':s2surplus,'s2surpluscounter':s2surpluscounter,
  'q2regard':q2regard,'q2regardcounter':q2regardcounter,'q2surplus':q2surplus,'q2surpluscounter':q2surpluscounter,
  'v2':v2,'thd2':thd2,'cosphi2':cosphi2,
  'p3regard':p3regard,'p3regardcounter':p3regardcounter,'p3surplus':p3surplus,'p3surpluscounter':p3surpluscounter,
  's3regard':s3regard,'s3regardcounter':s3regardcounter,'s3surplus':s3surplus,'s3surpluscounter':s3surpluscounter,
  'q3regard':q3regard,'q3regardcounter':q3regardcounter,'q3surplus':q3surplus,'q3surpluscounter':q3surpluscounter,
  'v3':v3,'thd3':thd3,'cosphi3':cosphi3 }
  return emparts
```
(Seems like I finally did get the hang of how to paste stuff here...)

**Comment by stei-f** [comment]
I did tweak this version a bit further
- cleanup and streamlining 
- write values directly to the emparts dict, which has the advantage of having optional values if they are readable 
- providing the version

If someone is interested, I can provide the file/code...

**Comment by datenschuft** [comment]
with the last commit on master branch the problems should get solved
