### ISSUE TITLE
mqtts support

### ISSUE THREAD

**Issue by Hooch76** [datenschuft/SMA-EM#25]
Hi,

I have seen that there is also mqtt support using https://github.com/datenschuft/SMA-EM/blob/master/features/mqtt.py
It is using the paho.mqtt.client. Would it be possible to also add mqtts support? It seems as if the client does support it: https://pypi.org/project/paho-mqtt/#constructor-reinitialise (TLS_SET()). My python skills are not good enough unfortunately.

Thanks,
Tom

**Comment by datenschuft** [comment]
Hi Hooch76
sorry about the delay, 
currently i'm not using mqtt...
maybe i reinstall my mqtt-server and test tls mqtt connections... stay tuned

**Comment by Tommi2Day** [comment]
I am taking a look into

**Comment by datenschuft** [comment]
merged ... thanks @Tommi2Day
