### ISSUE TITLE
parsing error in pvdata.py

### ISSUE THREAD

**Issue by AnduriI** [datenschuft/SMA-EM#31]
Hello,

I tried to get pvdata feature working. In case I deactivate this feature it works fine. With pvdata enabled it throws an error every ~20s, but the normal messagen still work (every ~5s).

```
mqtt: sma-em data published 21:18:56:{"pusage": 1478.6, "psupply": 0.0, "pconsume": 1478.6, "timestamp": 1600024736.601813, "pvsum": 0}
mqtt: sma-em data published 21:19:01:{"pusage": 1483.1, "psupply": 0.0, "pconsume": 1483.1, "timestamp": 1600024741.6097176, "pvsum": 0}
mqtt: sma-em data published 21:19:07:{"pusage": 1466.9, "psupply": 0.0, "pconsume": 1466.9, "timestamp": 1600024747.6077533, "pvsum": 0}
Daemon: Exception occured
unexpected EOF while parsing (<string>, line 1)
mqtt: sma-em data published 21:19:13:{"pusage": 1528.9, "psupply": 0.0, "pconsume": 1528.9, "timestamp": 1600024753.6029267, "pvsum": 0}
mqtt: sma-em data published 21:19:19:{"pusage": 1498.7, "psupply": 0.0, "pconsume": 1498.7, "timestamp": 1600024759.6023366, "pvsum": 0}
mqtt: sma-em data published 21:19:25:{"pusage": 1543.2, "psupply": 0.0, "pconsume": 1543.2, "timestamp": 1600024765.5953574, "pvsum": 0}
mqtt: sma-em data published 21:19:31:{"pusage": 1529.0, "psupply": 0.0, "pconsume": 1529.0, "timestamp": 1600024771.5965288, "pvsum": 0}
Daemon: Exception occured
unexpected EOF while parsing (<string>, line 1)
mqtt: sma-em data published 21:19:37:{"pusage": 1498.0, "psupply": 0.0, "pconsume": 1498.0, "timestamp": 1600024777.5955472, "pvsum": 0}
mqtt: sma-em data published 21:19:43:{"pusage": 1518.4, "psupply": 0.0, "pconsume": 1518.4, "timestamp": 1600024783.5970316, "pvsum": 0}
```

```
[FEATURE-pvdata]
# How frequently to send updates over (defaults to 20 sec)
min_update=20
debug=0
inv_host = 192.168.38.142
inv_port = 502
inv_modbus_id = 3
inv_manufacturer = SMA
registers = [
#['address', 'type', 'format', 'description', 'unit', 'value'],
['30057', 'U32', 'RAW', 'serial', ''],
['30201','U32','ENUM','Status',''],
['30775', 'S32', 'FIX0', 'AC Power', 'W']]
```

Maybe @Tommi2Day can help as he created this feature. I cannot find the reason for that `EOF while parsing` and it does not give further information about it's origin.

Best regards,
Anduril

**Comment by Tommi2Day** [comment]
Hi @AnduriI ,
I have no glue at this time. Never saw this before. Pls activate pvdata debug in your config and link it here. hopefully there is more related to this error. Pls anonymize the log before uploading

**Comment by AnduriI** [comment]
I will post the debug... when I find it. Where is this stored?

**Comment by Tommi2Day** [comment]
unfortunally, there is currently no direct debug to file available. pls. set debug=1 in pvdata, stop the daemon and start the daemon with the "run" instead of "start" command and capture the output to file (usually |tee pvdata.log) to catch some of the error messages

**Comment by AnduriI** [comment]
`|tee didn't worked as expected, nothing happended to the sma-daemon after that command. I did activate the debug option in pvdata and monitored the stdout with the run option on my console. Nothing has changed here...
```mqtt: sma-em data published 21:42:51:{"pvsum": 0, "pconsume": 0.0, "psupply": 3.4, "pusage": -3.4, "timestamp": 1600112571.244344}
mqtt: sma-em data published 21:42:56:{"pvsum": 0, "pconsume": 0.7, "psupply": 0.0, "pusage": 0.7, "timestamp": 1600112576.2474825}
mqtt: sma-em data published 21:43:02:{"pvsum": 0, "pconsume": 0.0, "psupply": 19.9, "pusage": -19.9, "timestamp": 1600112582.2462313}
mqtt: sma-em data published 21:43:08:{"pvsum": 0, "pconsume": 0.0, "psupply": 3.9, "pusage": -3.9, "timestamp": 1600112588.2434313}
Daemon: Exception occured
unexpected EOF while parsing (<string>, line 1)
mqtt: sma-em data published 21:43:14:{"pvsum": 0, "pconsume": 0.0, "psupply": 7.9, "pusage": -7.9, "timestamp": 1600112594.2421353}
mqtt: sma-em data published 21:43:20:{"pvsum": 0, "pconsume": 2.5, "psupply": 0.0, "pusage": 2.5, "timestamp": 1600112600.2400296}
mqtt: sma-em data published 21:43:26:{"pvsum": 0, "pconsume": 6.0, "psupply": 0.0, "pusage": 6.0, "timestamp": 1600112606.2361028}
Daemon: Exception occured
unexpected EOF while parsing (<string>, line 1)
mqtt: sma-em data published 21:43:31:{"pvsum": 0, "pconsume": 0.6, "psupply": 0.0, "pusage": 0.6, "timestamp": 1600112611.2386665}
mqtt: sma-em data published 21:43:36:{"pvsum": 0, "pconsume": 0.0, "psupply": 10.0, "pusage": -10.0, "timestamp": 1600112616.2567458}
mqtt: sma-em data published 21:43:42:{"pvsum": 0, "pconsume": 20.2, "psupply": 0.0, "pusage": 20.2, "timestamp": 1600112622.237899}
mqtt: sma-em data published 21:43:48:{"pvsum": 0, "pconsume": 1.1, "psupply": 0.0, "pusage": 1.1, "timestamp": 1600112628.2349596}
```

Is it possible to add some debug printouts in your code to see what it tries to parse? I know that I have to sign in with a password to the inverter if I want to see any of its information.
Maybe it's a problem of having two of those in my network? I could also try to set the ip for the other one. Will it also work if I set the IP to my battery inverter (Sunny Boy Storage)?

**Comment by Tommi2Day** [comment]
you may set debug=1 within feature-pvdata section. after starting the daemon with run you should see similar this

> PV:{'device temperature': 61.8, 'DeviceClass': 'Solar Inverter', 'timestamp': 1600601994.6834853, 'grid frequency': 49.99, 'feed-in time': 29691157, 'DC input voltage': 358.67, 'AC Power': 6460, 'intermediate voltage': 586.44, 'Isolation resistance': 3000000, 'AC voltage': 230.91, 'total yield': 19566.042, 'AC apparent power': 6558, 'Power L1': 2158, 'Status': 'OK', 'AC current': 9.491, 'daily yield': 19.535, 'Power L3': 2155, 'serial': 30512xxxx, 'DeviceID': 'STP 10000TL-20', 'DC power': 3033, 'operation time': 30214779, 'Device Name': 'STP 10000TL-20 xxx', 'Power L2': 2153}

parsing the sma multicast broadcasts is done by smamodbus.py. It requires to set the right modbus adresses to match.There is also an feature "remote debug". If you own pycharm pro you may configure remote debugging load the sourcecode there and track the the code after setting a break point.

**Comment by Tommi2Day** [comment]
i found an potential issue in the mqtt code, which has been fixed(hopefully) along with the ssl implementation (MR #34 ). I also added there traceback to see where the exception you mentioned really happens. Maybe you can try this version

**Comment by AnduriI** [comment]
well, at least I see more error code... :+1: 
```
python3 sma-daemon.py run
mqtt: feature enabled
pvdata: feature enabled
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 11:07:12:{"pvdaily": 0, "pvsum": 0, "psupply": 0.0, "timestamp": 1600852032.7885792, "pconsume": 217.6, "pusage": 217.6}
Daemon: Exception occured
Traceback (most recent call last):
  File "sma-daemon.py", line 131, in run
    featurelist[featurenr]['feature'].run(emparts,featurelist[featurenr]['config'])
  File "/opt/smaemd/features/pvdata.py", line 74, in run
    pv_data = get_pv_data(config)
  File "/opt/smaemd/features/smamodbus.py", line 385, in get_pv_data
    registers = eval(config.get('registers'))
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing

mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 11:07:17:{"pvdaily": 0, "pvsum": 0, "psupply": 0.0, "timestamp": 1600852037.7935364, "pconsume": 1498.3, "pusage": 1498.3}
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 11:07:23:{"pvdaily": 0, "pvsum": 0, "psupply": 0.0, "timestamp": 1600852043.7964604, "pconsume": 208.6, "pusage": 208.6}
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 11:07:29:{"pvdaily": 0, "pvsum": 0, "psupply": 0.0, "timestamp": 1600852049.7873821, "pconsume": 71.0, "pusage": 71.0}
Daemon: Exception occured
Traceback (most recent call last):
  File "sma-daemon.py", line 131, in run
    featurelist[featurenr]['feature'].run(emparts,featurelist[featurenr]['config'])
  File "/opt/smaemd/features/pvdata.py", line 74, in run
    pv_data = get_pv_data(config)
  File "/opt/smaemd/features/smamodbus.py", line 385, in get_pv_data
    registers = eval(config.get('registers'))
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing

mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 11:07:34:{"pvdaily": 0, "pvsum": 0, "psupply": 0.0, "timestamp": 1600852054.790836, "pconsume": 5.4, "pusage": 5.4}
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 11:07:39:{"pvdaily": 0, "pvsum": 0, "psupply": 0.0, "timestamp": 1600852059.7965195, "pconsume": 13.6, "pusage": 13.6}
mqtt: ssl disabled
```

**Comment by Tommi2Day** [comment]
looks like your pv_data config registers settings are not valid python code. For me this works:
`registers = [
    ['30057', 'U32', 'RAW', 'serial', ''],
    ['30201','U32','ENUM','Status',''],
    ['30051','U32','ENUM','DeviceClass',''],
    ['30053','U32','ENUM','DeviceID',''],
    ['40631', 'STR32', 'UTF8', 'Device Name', ''],
    ['30775', 'S32', 'FIX0', 'AC Power', 'W'],
    ['30813', 'S32', 'FIX0', 'AC apparent power', 'VA'],
    ['30977', 'S32', 'FIX3', 'AC current', 'A'],
    ['30783', 'S32', 'FIX2', 'AC voltage', 'V'],
    ['30803', 'U32', 'FIX2', 'grid frequency', 'Hz'],
    ['30773', 'S32', 'FIX0', 'DC power', 'W'],
    ['30771', 'S32', 'FIX2', 'DC input voltage', 'V'],
    ['30777', 'S32', 'FIX0', 'Power L1', 'W'],
    ['30779', 'S32', 'FIX0', 'Power L2', 'W'],
    ['30781', 'S32', 'FIX0', 'Power L3', 'W'],
    ['30953', 'S32', 'FIX1', u'device temperature', u'\xb0C'],
    ['30517', 'U64', 'FIX3', 'daily yield', 'kWh'],
    ['30513', 'U64', 'FIX3', 'total yield', 'kWh'],
    ['30521', 'U64', 'FIX0', 'operation time', 's'],
    ['30525', 'U64', 'FIX0', 'feed-in time', 's'],
    ['30975', 'S32', 'FIX2', 'intermediate voltage', 'V'],
    ['30225', 'S32', 'FIX0', 'Isolation resistance', u'\u03a9']
    ]
`

**Comment by Tommi2Day** [comment]
MR#34 has been superseeded by #35, which includes more fixes

**Comment by AnduriI** [comment]
I just copied in your registers and that kind of worked... :-)
```mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:11:02:{"pconsume": 0.0, "psupply": 3.9, "timestamp": 1600859462.245233}
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:11:08:{"pconsume": 2.1, "psupply": 0.0, "timestamp": 1600859468.0846956}
2020-09-23 13:11:10: Connection not possible. Check settings or connection.
PV: no data
mqtt: ssl disabled
mqtt: sma-em topic SMA-EM/status/3007888915 data published 13:11:13:{"pconsume": 14.9, "psupply": 0.0, "timestamp": 1600859473.120726}
mqtt: ssl disabled
```
The config should be ok:
```[FEATURE-pvdata]
# How frequently to send updates over (defaults to 20 sec)
min_update=20
debug=1
inv_host = 192.168.38.141
inv_port = 502
inv_modbus_id = 3
inv_manufacturer = SMA
registers = [ ['30057', 'U32', 'RAW', 'serial', ''], ['30201','U32','ENUM','Sta$
```
Maybe that is because I had to set a password for the user group in the inverter-webinterface. Do you have your password still on factory default?

**Comment by Tommi2Day** [comment]
Your register settings looking like truncated at $, these are NOT OK. It should be valid python code, means proper count of brackets and ' and field count as well

**Comment by AnduriI** [comment]
That is just because I copied it from the console. The registers are exactly your code from the post above.
