### ISSUE TITLE
Feature Request: powerOut/energyIn

### ISSUE THREAD

**Issue by MichScha** [datenschuft/SMA-EM#37]
It seems that the multicast message also transports the alltime powerOut and energyIn values. As a reference: [Link](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java). Is it possible to integrated those values?

**Comment by Berlenz** [comment]
I analyzed the source code and found that the energy values are already included (see speedwiredecoder.py, line number 131).
The following list contains all possible field names that you can use with the feature mqtt, symcon, influxdb in the file /etc/smaemd/config:
pconsume,  pconsumeunit, pconsumecounter, pconsumecounterunit,
psupply,   psupplyunit,  psupplycounter,  psupplycounterunit,
qconsume,  qconsumeunit, qconsumecounter, qconsumecounterunit,
qsupply,   qsupplyunit,  qsupplycounter,  qsupplycounterunit,
sconsume,  sconsumeunit, sconsumecounter, sconsumecounterunit,
ssupply,   ssupplyunit,  ssupplycounter,  ssupplycounterunit,
cosphi,    cosphiunit,
frequency, frequencyunit,
p1consume, p1consumeunit, p1consumecounter, p1consumecounterunit,
p1supply,  p1supplyunit,  p1supplycounter,  p1supplycounterunit, 
q1consume, q1consumeunit, q1consumecounter, q1consumecounterunit, 
q1supply,  q1supplyunit,  q1supplycounter,  q1supplycounterunit, 
s1consume, s1consumeunit, s1consumecounter, s1consumecounterunit, 
s1supply,  s1supplyunit,  s1supplycounter,  s1supplycounterunit, 
i1,        i1unit,
u1,        u1unit,
cosphi1,   cosphi1unit,
p2consume, p2consumeunit, p2consumecounter, p2consumecounterunit,
p2supply,  p2supplyunit,  p2supplycounter,  p2supplycounterunit, 
q2consume, q2consumeunit, q2consumecounter, q2consumecounterunit, 
q2supply,  q2supplyunit,  q2supplycounter,  q2supplycounterunit, 
s2consume, s2consumeunit, s2consumecounter, s2consumecounterunit, 
s2supply,  s2supplyunit,  s2supplycounter,  s2supplycounterunit, 
i2,        i2unit,
u2,        u2unit,
cosphi2,   cosphi2unit,
p3consume, p3consumeunit, p3consumecounter, p3consumecounterunit,
p3supply,  p3supplyunit,  p3supplycounter,  p3supplycounterunit, 
q3consume, q3consumeunit, q3consumecounter, q3consumecounterunit, 
q3supply,  q3supplyunit,  q3supplycounter,  q3supplycounterunit, 
s3consume, s3consumeunit, s3consumecounter, s3consumecounterunit, 
s3supply,  s3supplyunit,  s3supplycounter,  s3supplycounterunit, 
i3,        i3unit,
u3,        u3unit,
cosphi3,   cosphi3unit,
speedwire-version

Example config where the power and energy of the consume item is published to the mqtt broker:
[FEATURE-mqtt]
mqttfields=pconsume,pconsumecounter

**Comment by Berlenz** [comment]
I have added the possible filed names to 'config.sample' file and created a pull request.

**Comment by MichScha** [comment]
Nice, thank you very much for clarification. Works!
