### ISSUE TITLE
Patch: Output for more than one EM and more output per EM

### ISSUE THREAD

**Issue by kettenbach-it** [datenschuft/SMA-EM#4]
This patch enables more output and a distinct file per EM

[smaem.moreoutput.patch.txt](https://github.com/datenschuft/SMA-EM/files/184585/smaem.moreoutput.patch.txt)

**Comment by datenschuft** [comment]
SMA-EM-Daemon could now handle more SMA-EMs.
You can also configure the measurement values in the config-file /etc/smaemd/config
it generates /run/shm/em-[serial]-[value] - files
value = label in returning values in smaem.py
