### ISSUE TITLE
KeyError: 'pconsume'

### ISSUE THREAD

**Issue by nona00** [datenschuft/SMA-EM#51]
----sum----
P: consume:0.0W 1330.7514kWh supply:4.2W 83.867kWh
S: consume:0.0VA 1999.4009kVAh supply:296.1VA 244.1794VAh
Q: cap 0.0var 0.7763kvarh ind 296.1var 1408.9223kvarh
cos phi:0.014°
----L1----
P: consume:0.0W 832.6387kWh supply:75.7W 183.5639kWh
S: consume:0.0VA 1080.0089kVAh supply:173.7VA 228.3474kVAh
Q: cap 0.0var 9.2341kvarh ind 156.3var 623.1292kvarh
U: 234.505V I:1.085A cos phi:0.436°
----L2----
P: consume:37.1W 538.1752kWh supply:0.0W 166.6808kWh
S: consume:68.8VA 714.0687kVAh supply:0.0VA 177.0364kVAh
Q: cap 0.0var 1.3742kvarh ind 58.0var 387.3873kvarh
U: 235.332V I:0.377A cos phi:0.539°
----L3----
P: consume:34.4W 416.6163kWh supply:0.0W 190.3011kWh
S: consume:88.7VA 640.1808kVAh supply:0.0VA 205.2369kVAh
Q: cap 0.0var 2.9743kvarh ind 81.8var 411.2119kvarh
U: 234.244V I:0.518A cos phi:0.388°
Version: 2.5.9.R|020509

SMA-EM Serial:XXXXXXXX
----sum----
Traceback (most recent call last):
  File "./sma-em-measurement.py", line 84, in <module>
    print ('P: consume:{}W {}kWh supply:{}W {}kWh'.format(emparts['pconsume'],emparts['pconsumecounter'],emparts['psupply'],emparts['psupplycounter']))
KeyError: 'pconsume'

**Comment by datenschuft** [comment]
maybe there is something wrong with your datagrams; because consuming 37.1W and 34,4W on phase 2 and 3 is not 0 in summary and pconsume was already shown in section ---sum--- P: consume:0.0W
