### ISSUE TITLE
Datei wird nicht erstellt

### ISSUE THREAD

**Issue by Flippo710** [datenschuft/SMA-EM#71]
Moin,

habe das Script nach Anleitung installiert. Keinerlei Fehlermeldung erhalten, allerdings werden keine Dateien erstellt. 

Gibt es eine Art log, an dem man nachvollziehen kann, an welcher Stelle es hängt?

Danke und VG,
Philipp

**Comment by datenschuft** [comment]
Man kann den Daemon mit dem Parameter run starten, dann sollte er im Vordergrund laufen und ggf. Fehler anzeigen.
Einzelne Features unterstützen die Aktivierung der Debug Option, wodurch mehr informationen ausgegeben werden.
